config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create] do
    get 'videos', on: :member
  end

  resources :share_videos, only: %i[new create] do
    get 'my_videos', on: :collection
  end
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#signout'
  get 'signup', to: 'users#new'
  root to: 'main#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/share_video.rb
class ShareVideo < ApplicationRecord
  belongs_to :user

  before_save :info_from_yt

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  validates :video_url, presence: true, format: YT_LINK_FORMAT

  def info_from_yt
    video = Yt::Video.new url: video_url
    if video
      self.uid = video.id
      self.title = video.title
      self.likes = video.like_count
      self.dislikes = video.dislike_count
      self.published_at = video.published_at
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :share_videos, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def check_login
    redirect_to '/' unless logged_in?
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# Main Controller
class MainController < ApplicationController
  def home
    @videos = ShareVideo.order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @error_msg = 'Wrong Username or Password, Please try again!!'
      render 'new'
    end
  end

  def signout
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/share_videos_controller.rb
class ShareVideosController < ApplicationController
  before_action :check_login

  def my_videos
    @videos = current_user.share_videos
  end

  def new
    @share_video = current_user.share_videos.new
  end

  def create
    @share_video = current_user.share_videos.new(video_params)
    if @share_video.save
      flash[:success] = 'Video added!'
      redirect_to my_videos_share_videos_url
    else
      render 'new'
    end
  end

  private

  def video_params
    params.require(:share_video).permit(:video_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/share_videos_helper.rb
module ShareVideosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funnytube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://www.google.com/jsapi"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
  </head>

  <body>
    <header class="header">
      <div class="header-top">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <div class="top-sitemap text-left">
                <% if logged_in? %>
                  <span><i class="fa fa-user"></i><%= current_user.email %></span>
                  <span><a href="/signout" data-method='delete'><i class="fa fa-lock"></i> Sign Out</a></span>
                <% else %>
                  <span> <a href="/signin"><i class="fa fa-lock"></i> Sign In</a></span>
                  <span><a href="/signup"><i class="fa fa-user"></i> Register</a></span>
                <% end %>
              </div><!-- /.top-sitemap -->
            </div>
          </div><!-- /.row -->
        </div><!-- /.container -->
      </div><!-- /.header-top -->

      <div class="header-middle">
        <div class="container">
          <div class="row">
            <div class="col-sm-3">
              <div class="navbar-brand hidden-xs"><a href="/"><span class="logo-text">FunnyTUBE</span></a></div>
            </div>
          </div>
        </div>
      </div><!-- /.header-middle -->

      <div class="header-bottom">
        <div class="container">
          <div class="row">
            <div class="col-sm-7">
              <nav class="navbar navbar-default">
                <div class="navbar-header visible-xs">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                    <i class="fa fa-bars"></i>
                  </button>
                </div>

                <div id="menu" class="main-menu collapse navbar-collapse pull-left">

                  <ul class="nav navbar-nav">

                    <li class="menu-item active">
                      <a href="/">Home</a>
                    </li>

                    <li class="menu-item menu-item-has-children">
                      <a href="#">Categories</a>
                      <ul class="sub-menu children">
                        <li><a href="#">Funny</a></li>
                        <li><a href="#">Sport</a></li>
                        <li><a href="#">Food</a></li>
                        <li><a href="#">Travel</a></li>
                      </ul>
                    </li>
                    <% if logged_in? %>
                      <li class="menu-item menu-item-has-children">
                        <a href="#">My account</a>
                        <ul class="sub-menu children">
                          <li><%= link_to "My Videos", my_videos_share_videos_url %></li>
                          <li><%= link_to "Share Video", new_share_video_url %></li>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </nav><!-- /.navbar -->
            </div>
          </div>
        </div><!-- /.container -->
      </div><!-- /.header-bottom -->
    </header><!-- /.header -->
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<section class="latest-posts two-column">
  <div class="section-padding">
    <div class="container">
      <div class="row">
        <h2 class="section-title">Latest Videos</h2><!-- /.section-title -->

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/614933078.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/201203170" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/615779278.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/201893063" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/619810596.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/205127149" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/614767642.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/200996814" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/614336407.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/200749722" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/614885074.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/201046241" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/619412434.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/204815517" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="col-sm-6">
          <article class="post type-post">
            <div class="entry-thumbnail">
              <img src="https://i.vimeocdn.com/video/614535805.jpg?mw=1920&mh=1080" alt="Item Thumbnail">
              <a href="https://vimeo.com/200900100" class="iframe">
                <span class="play-video"><i class="fa fa-play-circle-o"></i></span>
              </a>
            </div><!-- /.entry-thumbnail -->
            <div class="entry-content">
              <h2 class="entry-title"><a href="video-03.html">Chris Pratt and Jennifer Lawrence Answer the Internet's Most Asked Questions</a></h2><!-- /.entry-title -->
              <div class="entry-meta">
                <span class="author"><a href="#">VideoBlogger</a></span><!-- /.author -->
                <span><i class="fa fa-clock-o"></i> <time datetime="PT5M">5 months</time></span>
                <span><a href="#"><i class="fa fa-comment-o"></i> <span class="count">351</span></a></span>
                <span><i class="fa fa-eye"></i> <span class="count">17,989</span></span>
              </div><!-- /.entry-meta -->
            </div><!-- /.entry-content -->
          </article><!-- /.post -->
        </div>

        <div class="btn-container text-center clearfix"><a href="#" class="btn read-more">Load more</a></div><!-- /.btn-container -->

      </div>
    </div><!-- /.container -->
  </div><!-- /.section-padding -->
</section><!-- /.video-content -->

app/views/share_videos/_video.html.erb
<div class="col-sm-6">
  <article class="post type-post">
    <div class="entry-thumbnail">
      <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                            class: 'img-rounded'),
                  "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
    </div><!-- /.entry-thumbnail -->
    <div class="entry-content">
      <h2 class="entry-title"><%= video.title %></h2>
      <div class="entry-meta">
        <span><i class="fa fa-clock-o"></i> <time datetime="PT5M"><%= video.published_at.strftime('%-d %B %Y') %></time></span>
        <span><i class="glyphicon glyphicon glyphicon-thumbs-up"></i> <span class="count"><%= video.likes %></span></span>
        <span><i class="glyphicon glyphicon glyphicon-thumbs-down"></i> <span class="count"><%= video.dislikes %></span></span>
      </div><!-- /.entry-meta -->
    </div><!-- /.entry-content -->
  </article><!-- /.post -->
</div>

app/views/share_videos/my_videos.html.erb
<section class="latest-posts two-column">
  <div class="section-padding">
    <div class="container">
      <div class="row">
        <h2 class="section-title">My Videos</h2><!-- /.section-title -->
        <div id="player-wrapper"></div>
        <% @videos.each do |video| %>
          <%= render partial: 'video', locals: {video: video} %>
        <% end %>
      </div>
    </div><!-- /.container -->
  </div><!-- /.section-padding -->
</section><!-- /.video-content -->

app/views/share_videos/new.html.erb
<section class="author-page-contents">
  <div class="section-padding">
    <div class="container">
      <div class="author-contents">
        <div class="row">
          <h2 class="section-title">Share Video</h2><!-- /.section-title -->
          <div class="col-sm-8">
            <div class="about-author">
              <div class="upload-video">
                <%= form_for @share_video, html: {class: 'upload-form' } do |f| %>
                  <p class="form-element">
                    <%= f.label :video_url %>
                    <%= f.text_field :video_url, class:'title form-control', required: true %>
                  </p>
                  <%= f.submit class: 'submit' %>
                <% end %>
              </div><!-- /.upload-video -->
            </div><!-- /.about-author -->
          </div>
        </div>
      </div>
    </div><!-- /.container -->
  </div><!-- /.section-padding -->
</section><!-- /.author-page-contents -->

app/views/users/new.html.erb
<section class="form-elements style-2">
  <div class="section-padding">
    <div class="right-panel">
      <h4>Create Your Account</h4>
      <%= form_for @user, html: {class:'register-form'} do |f| %>
        <p class="form-input">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </p>
        <p class="form-input">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </p>
        <p class="submit-input">
          <input type="submit" class="btn" name="signup-form-submit" value="Register Now">
        </p>
      <% end %>
    </div><!-- /.right-panel -->
    <span class="bottom-text">
      Already Have an Account? <a href="/signin">Sign In</a>
    </span>
  </div><!-- /.section-padding -->
</section><!-- /.form-elements -->

app/views/videos/new.html.erb
<section class="author-page-contents">
  <div class="section-padding">
    <div class="container">
      <div class="author-contents">
        <div class="row">
          <h2 class="section-title">Share Video</h2><!-- /.section-title -->
          <div class="col-sm-8">
            <div class="about-author">
              <div class="upload-video">
                <%= form_for @video, html: {class: 'upload-form' } do |f| %>
                  <p class="form-element">
                    <%= f.label :link %>
                    <%= f.text_field :link, class:'title form-control', required: true %>
                  </p>
                  <%= f.submit class: 'submit' %>
                <% end %>
              </div><!-- /.upload-video -->
            </div><!-- /.about-author -->
          </div>
        </div>
      </div>
    </div><!-- /.container -->
  </div><!-- /.section-padding -->
</section><!-- /.author-page-contents -->